//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string productName { get; set; }
        public int productIAmount { get; set; }
        public decimal productUnitValue { get; set; }
        public decimal productTotalValue { get; set; }
        public int clientId { get; set; }
        public string clientName { get; set; }

        public client client { get; set; }
        public product product { get; set; }
    }
}
